### PR TITLE
Further development

### PR DESCRIPTION
**Pull request by habnabit**
I've done a lot more stuff!

I'm not sure at this point how to consolidate development or anything, especially since I've taken everything in a very different direction at this point. It does code generation with pom/synom from .tl files, because duplicating all that by hand is a pain. Telegram layers are becoming more complicated and the json schema is woefully out of date still.

### CODE REVIEW

**Comment by habnabit** [comment]
Also I'm not really sure how interested you are in developing this yourself at this point.

**Comment by Connicpu** [comment]
I have a lot of other projects on my plate still. You seem much more motivated in continuing the development of this library than I, so I'm happy to trust your judgement on getting it further along! How about I add you as a proper collaborator on the repository?

**Comment by habnabit** [comment]
Yay thanks!

**Comment by habnabit** [comment]
Btw, there's a `#telegram` channel on mozilla irc where some coordination is happening.

**Pull request merged**
